"""Initial migration 2

Revision ID: 7c4d7be6b78a
Revises: 061072b78dea
Create Date: 2020-08-04 01:50:47.548592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4d7be6b78a'
down_revision = '061072b78dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_updates', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_updates', 'created_at')
    # ### end Alembic commands ###
