"""Initial migration

Revision ID: 26528292161a
Revises: 
Create Date: 2020-08-04 01:14:25.901285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26528292161a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_process', 'completed', 'failed', name='stauts'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__price_updates'))
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=True),
    sa.Column('city_from_code', sa.String(length=3), nullable=False),
    sa.Column('city_to_code', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('booking_token,', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['update_id'], ['price_updates.id'], name=op.f('fk__flights__update_id__price_updates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__flights'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('price_updates')
    # ### end Alembic commands ###
